services:
  node_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_app
    ports:
      - "3000:3000"
    # environment:
    #   - PORT=3000
    #   - DB_HOST=mysql
    #   - DB_USER=root
    #   - DB_PASSWORD=rootpassword
    #   - DB_NAME=mediator_app
    #   - JWT_SECRET=jwtsecretmediator_application
    env_file:
      - .env 
    depends_on:
      - mysql
    volumes:
      - .:/app

  mysql:
    image: mysql:9
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD} #rootpassword
      MYSQL_DATABASE:  ${DB_NAME} # mediator_app
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
