version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mediator-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: mediator_phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - mysql
    networks:
      - mediator-network

  node_app:
    depends_on:
      - mysql
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mediator_node_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/mediator_node_app
      - /mediator_node_app/node_modules
    command: ["npm", "run", "dev"]
    networks:
      - mediator-network

volumes:
  mysql_data:

networks:
  mediator-network:
    driver: bridge
